name: Build, Lint, and Format Code

on: pull_request

jobs:
  Verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node
        uses: actions/setup-node@v4.1.0

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm build

      - name: Format
        run: npm lint

      - name: Lint
        run: npm lint

      - name: Commit changes if any
        uses: actions-x/commit@v6

  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node
        uses: actions/setup-node@v4.1.0

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm build

      - name: Prepare Artifact
        run: |
